"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import "./clients.css";

type Client={id:string;name:string;primary_contact_name:string;primary_contact_email:string;status:string;created_at:string;client_users?:Array<{email:string;role:string}>;projects?:Array<{id:string;name:string;status:string;progress:number}>};
export default function ClientsAdmin(){const[clients,setClients]=useState<Client[]>([]);const[authorized,setAuthorized]=useState<boolean|null>(null);const[form,setForm]=useState({company:"",contact_name:"",email:"",password:""});const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
 async function load(){const r=await fetch("/api/admin/clients",{cache:"no-store"});if(r.status===401){setAuthorized(false);return}const p=await r.json();setClients(p.clients||[]);setAuthorized(true)}useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");const r=await fetch("/api/admin/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const p=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setMessage(p.error||"Could not create client.");return}setMessage("Client workspace created. Share the portal email and temporary password securely.");setForm({company:"",contact_name:"",email:"",password:""});await load()}
 if(authorized===false)return <main className="clients-auth"><div><h1>Client Management</h1><p>Your admin session is not active.</p><Link href="/admin">Sign in through Lead Cockpit</Link></div></main>;
 return <main className="clients-shell"><nav className="admin-nav"><Link href="/admin">Lead Cockpit</Link><Link href="/admin/analytics">Analytics</Link><Link href="/admin/copy-studio">AI Copy Studio</Link><Link href="/admin/proposals">Proposals</Link><Link className="active" href="/admin/clients">Clients</Link></nav><header><div><span>DAVIDPILOT · CLIENT OPERATIONS</span><h1>Client Management</h1><p>Create secure client workspaces and manage access to the DavidPilot Client Portal.</p></div><a href="/portal/login" target="_blank">Open Client Portal ↗</a></header><section className="clients-layout"><form className="client-create" onSubmit={create}><span>NEW CLIENT WORKSPACE</span><h2>Create client access</h2><label>Company<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})} required/></label><label>Primary contact<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Temporary password<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>{message&&<p className="client-message">{message}</p>}<button disabled={loading}>{loading?"Creating…":"Create workspace"}</button><small>Use a unique temporary password and share it through a secure channel. Password reset and invitation emails are planned for the next portal iteration.</small></form><section className="client-list"><div className="section-head"><div><span>CLIENTS</span><h2>{clients.length} workspaces</h2></div></div>{clients.length?clients.map(c=><article key={c.id}><Link className="client-manage-link" href={`/admin/clients/${c.id}`}>Manage workspace →</Link><div className="client-top"><div><span>{c.status}</span><h3>{c.name}</h3><p>{c.primary_contact_name} · {c.primary_contact_email}</p></div><strong>{c.projects?.length||0}<small>projects</small></strong></div><div className="client-meta"><span>Portal user: {c.client_users?.[0]?.email||"Not assigned"}</span><span>Created {new Date(c.created_at).toLocaleDateString()}</span></div></article>):<p className="empty">No client workspaces yet.</p>}</section></section></main>}
