"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import "./client-detail.css";

type AnyRow=Record<string,any>;
const projectStatuses=["planning","active","blocked","completed","cancelled"];
const milestoneStatuses=["pending","in_progress","completed","blocked"];
const meetingStatuses=["scheduled","completed","cancelled"];
const supportStatuses=["open","in_progress","resolved","closed"];

export default function ClientDetail(){
 const routeParams=useParams<{id:string}>(); const id=routeParams?.id||""; const[data,setData]=useState<any>(null); const[tab,setTab]=useState("overview"); const[message,setMessage]=useState(""); const[busy,setBusy]=useState(false);
 const[project,setProject]=useState({name:"",description:"",status:"planning",progress:0,starts_at:"",target_date:""});
 const[milestone,setMilestone]=useState({project_id:"",title:"",status:"pending",due_at:""});
 const[meeting,setMeeting]=useState({project_id:"",title:"",starts_at:"",ends_at:"",status:"scheduled",meeting_url:"",notes:""});
 const[docForm,setDocForm]=useState({project_id:"",title:"",category:"",url:"",description:""});
 async function load(target=id){if(!target)return;const r=await fetch(`/api/admin/clients/${target}`,{cache:"no-store",credentials:"include"});if(r.status===401){location.href="/admin";return}const p=await r.json();setData(p)}
 useEffect(()=>{if(id)load(id)},[id]);
 async function act(payload:AnyRow){setBusy(true);setMessage("");const r=await fetch(`/api/admin/clients/${id}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMessage(p.error||"Operation failed.");return false}setMessage("Saved successfully.");await load();return true}
 const assignedProposals=useMemo(()=>data?.proposals?.filter((p:AnyRow)=>p.client_id===id)||[],[data,id]);
 const availableProposals=useMemo(()=>data?.proposals?.filter((p:AnyRow)=>!p.client_id)||[],[data]);
 if(!data?.client)return <main className="client-detail-loading">Loading client workspace…</main>;
 const c=data.client;
 return <main className="client-detail-shell">
  <nav className="ops-nav"><Link href="/admin">Lead Cockpit</Link><Link href="/admin/analytics">Analytics</Link><Link href="/admin/copy-studio">AI Copy Studio</Link><Link href="/admin/proposals">Proposals</Link><Link className="active" href="/admin/clients">Clients</Link></nav>
  <header className="client-detail-header"><div><Link href="/admin/clients">← Clients</Link><span>DAVIDPILOT · CLIENT OPERATIONS</span><h1>{c.name}</h1><p>{c.primary_contact_name} · {c.primary_contact_email}</p></div><div className="header-actions"><span className={`status ${c.status}`}>{c.status}</span><button disabled={busy} onClick={()=>act({action:"send_password_reset"})}>Send password reset</button><a href="/portal/login" target="_blank">Open portal ↗</a></div></header>
  <nav className="client-tabs">{["overview","projects","meetings","documents","proposals","support","activity"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</nav>
  {message&&<p className="ops-message">{message}</p>}
  {tab==="overview"&&<section className="overview-grid"><div className="metric"><span>Projects</span><strong>{data.projects.length}</strong></div><div className="metric"><span>Active projects</span><strong>{data.projects.filter((p:AnyRow)=>p.status==="active").length}</strong></div><div className="metric"><span>Meetings</span><strong>{data.meetings.length}</strong></div><div className="metric"><span>Open support</span><strong>{data.support.filter((s:AnyRow)=>!["resolved","closed"].includes(s.status)).length}</strong></div><article className="panel profile-panel"><h2>Client profile</h2><div className="profile-grid"><label>Company<input defaultValue={c.name} id="client-name"/></label><label>Contact<input defaultValue={c.primary_contact_name||""} id="client-contact"/></label><label>Email<input defaultValue={c.primary_contact_email||""} id="client-email"/></label><label>Status<select defaultValue={c.status} id="client-status"><option>active</option><option>onboarding</option><option>paused</option><option>closed</option></select></label></div><button disabled={busy} onClick={()=>act({action:"update_client",name:(document.getElementById("client-name") as HTMLInputElement).value,primary_contact_name:(document.getElementById("client-contact") as HTMLInputElement).value,primary_contact_email:(document.getElementById("client-email") as HTMLInputElement).value,status:(document.getElementById("client-status") as HTMLSelectElement).value})}>Save client profile</button></article></section>}
  {tab==="projects"&&<section className="two-col"><form className="panel form-panel" onSubmit={async e=>{e.preventDefault();if(await act({action:"create_project",...project}))setProject({name:"",description:"",status:"planning",progress:0,starts_at:"",target_date:""})}}><span>NEW PROJECT</span><h2>Create project</h2><label>Name<input required value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/></label><label>Description<textarea value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/></label><div className="form-grid"><label>Status<select value={project.status} onChange={e=>setProject({...project,status:e.target.value})}>{projectStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" value={project.progress} onChange={e=>setProject({...project,progress:Number(e.target.value)})}/></label><label>Start date<input type="date" value={project.starts_at} onChange={e=>setProject({...project,starts_at:e.target.value})}/></label><label>Target date<input type="date" value={project.target_date} onChange={e=>setProject({...project,target_date:e.target.value})}/></label></div><button disabled={busy}>Create project</button></form><div className="stack">{data.projects.map((p:AnyRow)=><ProjectCard key={p.id} p={p} milestones={data.milestones.filter((m:AnyRow)=>m.project_id===p.id)} onSave={(v)=>act({action:"update_project",id:p.id,...v})} onMilestone={(v)=>act({action:"create_milestone",project_id:p.id,...v})}/>)}</div></section>}
  {tab==="meetings"&&<section className="two-col"><form className="panel form-panel" onSubmit={async e=>{e.preventDefault();if(await act({action:"create_meeting",...meeting}))setMeeting({project_id:"",title:"",starts_at:"",ends_at:"",status:"scheduled",meeting_url:"",notes:""})}}><span>NEW MEETING</span><h2>Add meeting</h2><label>Project<select value={meeting.project_id} onChange={e=>setMeeting({...meeting,project_id:e.target.value})}><option value="">General / no project</option>{data.projects.map((p:AnyRow)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Title<input required value={meeting.title} onChange={e=>setMeeting({...meeting,title:e.target.value})}/></label><div className="form-grid"><label>Starts<input required type="datetime-local" value={meeting.starts_at} onChange={e=>setMeeting({...meeting,starts_at:e.target.value})}/></label><label>Ends<input type="datetime-local" value={meeting.ends_at} onChange={e=>setMeeting({...meeting,ends_at:e.target.value})}/></label><label>Status<select value={meeting.status} onChange={e=>setMeeting({...meeting,status:e.target.value})}>{meetingStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Meeting URL<input value={meeting.meeting_url} onChange={e=>setMeeting({...meeting,meeting_url:e.target.value})}/></label></div><label>Notes<textarea value={meeting.notes} onChange={e=>setMeeting({...meeting,notes:e.target.value})}/></label><button disabled={busy}>Add meeting</button></form><div className="stack">{data.meetings.map((m:AnyRow)=><article className="panel resource-card" key={m.id}><span>{m.status}</span><h3>{m.title}</h3><p>{new Date(m.starts_at).toLocaleString()}</p>{m.meeting_url&&<a href={m.meeting_url} target="_blank">Join / open link ↗</a>}</article>)}</div></section>}
  {tab==="documents"&&<section className="two-col"><form className="panel form-panel" onSubmit={async e=>{e.preventDefault();if(await act({action:"create_document",...docForm}))setDocForm({project_id:"",title:"",category:"",url:"",description:""})}}><span>NEW DOCUMENT</span><h2>Share document</h2><label>Project<select value={docForm.project_id} onChange={e=>setDocForm({...docForm,project_id:e.target.value})}><option value="">General</option>{data.projects.map((p:AnyRow)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Title<input required value={docForm.title} onChange={e=>setDocForm({...docForm,title:e.target.value})}/></label><label>Category<input value={docForm.category} onChange={e=>setDocForm({...docForm,category:e.target.value})}/></label><label>URL<input value={docForm.url} onChange={e=>setDocForm({...docForm,url:e.target.value})}/></label><label>Description<textarea value={docForm.description} onChange={e=>setDocForm({...docForm,description:e.target.value})}/></label><button disabled={busy}>Share document</button></form><div className="stack">{data.documents.map((d:AnyRow)=><article className="panel resource-card" key={d.id}><span>{d.category||"document"}</span><h3>{d.title}</h3><p>{d.description}</p>{d.url&&<a href={d.url} target="_blank">Open document ↗</a>}</article>)}</div></section>}
  {tab==="proposals"&&<section className="two-col"><div className="panel form-panel"><span>SHARE PROPOSAL</span><h2>Assign existing proposal</h2>{availableProposals.length?availableProposals.map((p:AnyRow)=><div className="proposal-row" key={p.id}><div><strong>{p.title}</strong><small>{p.status} · {p.language?.toUpperCase()}</small></div><button onClick={()=>act({action:"link_proposal",proposal_id:p.id,status:"shared"})}>Share</button></div>):<p className="muted">No unassigned proposals available.</p>}<Link className="secondary-link" href="/admin/proposals">Generate proposal →</Link></div><div className="stack">{assignedProposals.map((p:AnyRow)=><article className="panel resource-card" key={p.id}><span>{p.status}</span><h3>{p.title}</h3><p>{p.timeline||"Timeline TBD"}</p><small>€{p.investment_min??"—"} – €{p.investment_max??"—"}</small></article>)}</div></section>}
  {tab==="support"&&<section className="stack">{data.support.length?data.support.map((s:AnyRow)=><SupportCard key={s.id} s={s} onSave={(v)=>act({action:"update_support",id:s.id,...v})}/>):<p className="empty">No support requests.</p>}</section>}
  {tab==="activity"&&<section className="activity-list">{data.activity.map((a:AnyRow)=><article key={a.id}><span>{new Date(a.created_at).toLocaleString()}</span><strong>{a.label}</strong><small>{a.type}</small></article>)}</section>}
 </main>
}

function ProjectCard({p,milestones,onSave,onMilestone}:{p:AnyRow;milestones:AnyRow[];onSave:(v:AnyRow)=>void;onMilestone:(v:AnyRow)=>void}){const[v,setV]=useState({...p});const[m,setM]=useState({title:"",status:"pending",due_at:""});return <article className="panel project-card"><div className="project-head"><div><span>{v.status}</span><h3>{v.name}</h3></div><strong>{v.progress}%</strong></div><label>Description<textarea value={v.description||""} onChange={e=>setV({...v,description:e.target.value})}/></label><div className="form-grid"><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{projectStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" value={v.progress} onChange={e=>setV({...v,progress:Number(e.target.value)})}/></label><label>Start<input type="date" value={v.starts_at||""} onChange={e=>setV({...v,starts_at:e.target.value})}/></label><label>Target<input type="date" value={v.target_date||""} onChange={e=>setV({...v,target_date:e.target.value})}/></label></div><button onClick={()=>onSave(v)}>Save project</button><div className="milestones"><h4>Milestones</h4>{milestones.map(x=><div className="milestone" key={x.id}><span>{x.status}</span><strong>{x.title}</strong><small>{x.due_at?new Date(x.due_at).toLocaleDateString():"No due date"}</small></div>)}<div className="milestone-form"><input placeholder="New milestone" value={m.title} onChange={e=>setM({...m,title:e.target.value})}/><select value={m.status} onChange={e=>setM({...m,status:e.target.value})}>{milestoneStatuses.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={m.due_at} onChange={e=>setM({...m,due_at:e.target.value})}/><button onClick={()=>{if(!m.title.trim())return;onMilestone(m);setM({title:"",status:"pending",due_at:""})}}>Add</button></div></div></article>}
function SupportCard({s,onSave}:{s:AnyRow;onSave:(v:AnyRow)=>void}){const[v,setV]=useState({...s});return <article className="panel support-card"><div><span>{v.priority} priority</span><h3>{v.subject}</h3><p>{v.message}</p></div><div className="form-grid"><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{supportStatuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}><option>low</option><option>normal</option><option>high</option></select></label></div><label>Admin response<textarea value={v.admin_response||""} onChange={e=>setV({...v,admin_response:e.target.value})}/></label><button onClick={()=>onSave(v)}>Save response</button></article>}
