"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import "./portal.css";

type PortalData={user:{email?:string};client:{id:string;name:string;primary_contact_name?:string;status?:string};role:string;projects:any[];milestones:any[];meetings:any[];documents:any[];proposals:any[];support:any[];activity:any[]};
const tabs=["Overview","Projects","Meetings","Documents","Proposals","Support"] as const;type Tab=typeof tabs[number];
function date(v?:string|null){return v?new Date(v).toLocaleString():"—"}
export default function ClientPortal(){
 const[data,setData]=useState<PortalData|null>(null);const[error,setError]=useState("");const[tab,setTab]=useState<Tab>("Overview");const[loading,setLoading]=useState(true);const[subject,setSubject]=useState("");const[message,setMessage]=useState("");const[priority,setPriority]=useState("normal");const[notice,setNotice]=useState("");const router=useRouter();
 async function load(){setLoading(true);const r=await fetch("/api/portal/dashboard",{cache:"no-store"});if(r.status===401){router.push("/portal/login");return}const payload=await r.json().catch(()=>({}));if(!r.ok){setError(payload.error||"Could not load portal.");setLoading(false);return}setData(payload);setLoading(false)}
 useEffect(()=>{load()},[]);
 const activeProjects=useMemo(()=>data?.projects.filter(p=>!["completed","cancelled"].includes(p.status)).length||0,[data]);
 const upcoming=useMemo(()=>data?.meetings.filter(m=>m.starts_at&&new Date(m.starts_at)>new Date()).length||0,[data]);
 async function submitSupport(e:React.FormEvent){e.preventDefault();setNotice("");const r=await fetch("/api/portal/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,message,priority})});const p=await r.json().catch(()=>({}));if(!r.ok){setNotice(p.error||"Could not submit request.");return}setSubject("");setMessage("");setPriority("normal");setNotice("Support request submitted.");await load()}
 if(loading)return <main className="portal-shell"><div className="portal-loading">Loading your workspace…</div></main>;
 if(error)return <main className="portal-shell"><div className="portal-error-card"><h1>Workspace unavailable</h1><p>{error}</p><Link href="/">Return to DavidPilot</Link></div></main>;
 if(!data)return null;
 return <main className="portal-shell"><aside className="portal-sidebar"><div className="portal-brand"><span>DP</span><div><strong>DAVIDPILOT</strong><small>Client Portal</small></div></div><nav>{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className="portal-side-foot"><small>Workspace</small><strong>{data.client.name}</strong><button onClick={async()=>{await fetch("/api/portal/logout",{method:"POST"});router.push("/portal/login")}}>Sign out</button></div></aside>
 <section className="portal-main"><header className="portal-header"><div><span className="portal-kicker">CLIENT WORKSPACE</span><h1>{tab}</h1><p>{data.client.name} · {data.user.email}</p></div><div className="portal-status">{data.client.status||"active"}</div></header>
 {tab==="Overview"&&<><section className="portal-metrics"><article><span>Active projects</span><strong>{activeProjects}</strong><small>Current delivery work</small></article><article><span>Upcoming meetings</span><strong>{upcoming}</strong><small>Scheduled sessions</small></article><article><span>Documents</span><strong>{data.documents.length}</strong><small>Shared files & resources</small></article><article><span>Open support</span><strong>{data.support.filter(s=>s.status!=="closed").length}</strong><small>Requests in progress</small></article></section><section className="portal-grid"><article className="portal-panel"><div className="panel-head"><span>PROJECTS</span><h2>Delivery at a glance</h2></div>{data.projects.length?data.projects.slice(0,4).map(p=><div className="project-row" key={p.id}><div><strong>{p.name}</strong><small>{p.status}</small></div><div className="progress"><i style={{width:`${Math.min(100,Math.max(0,p.progress||0))}%`}}/></div><b>{p.progress||0}%</b></div>):<p className="empty">Your projects will appear here once delivery begins.</p>}</article><article className="portal-panel"><div className="panel-head"><span>ACTIVITY</span><h2>Recent updates</h2></div>{data.activity.length?data.activity.slice(0,8).map(a=><div className="activity-row" key={a.id}><i/><div><strong>{a.label}</strong><small>{date(a.created_at)}</small></div></div>):<p className="empty">No recent client activity.</p>}</article></section></>}
 {tab==="Projects"&&<section className="portal-list-page">{data.projects.length?data.projects.map(p=><article className="portal-project" key={p.id}><div className="project-title"><div><span>{p.status}</span><h2>{p.name}</h2><p>{p.description||"DavidPilot delivery project"}</p></div><strong>{p.progress||0}%</strong></div><div className="progress large"><i style={{width:`${Math.min(100,Math.max(0,p.progress||0))}%`}}/></div><div className="milestones">{data.milestones.filter(m=>m.project_id===p.id).map(m=><div key={m.id} className={m.status==="completed"?"done":""}><i/><div><strong>{m.title}</strong><small>{m.status} · {m.due_at?new Date(m.due_at).toLocaleDateString():"No due date"}</small></div></div>)}</div></article>):<div className="empty-card">No projects assigned yet.</div>}</section>}
 {tab==="Meetings"&&<section className="portal-list-page">{data.meetings.length?data.meetings.map(m=><article className="portal-item" key={m.id}><div><span>{m.status}</span><h2>{m.title}</h2><p>{date(m.starts_at)}</p></div>{m.meeting_url&&<a href={m.meeting_url} target="_blank" rel="noreferrer">Join meeting</a>}</article>):<div className="empty-card">No meetings scheduled.</div>}</section>}
 {tab==="Documents"&&<section className="portal-list-page">{data.documents.length?data.documents.map(d=><article className="portal-item" key={d.id}><div><span>{d.category||"Document"}</span><h2>{d.title}</h2><p>{date(d.created_at)}</p></div>{d.url&&<a href={d.url} target="_blank" rel="noreferrer">Open</a>}</article>):<div className="empty-card">No documents shared yet.</div>}</section>}
 {tab==="Proposals"&&<section className="portal-list-page">{data.proposals.length?data.proposals.map(p=><article className="portal-item" key={p.id}><div><span>{p.status}</span><h2>{p.title}</h2><p>{p.timeline||"Timeline to be confirmed"} · {p.currency||"EUR"} {p.investment_min??"—"}{p.investment_max?`–${p.investment_max}`:""}</p></div></article>):<div className="empty-card">No proposals are shared with this workspace yet.</div>}</section>}
 {tab==="Support"&&<section className="portal-support"><form onSubmit={submitSupport} className="support-form"><span className="portal-kicker">DAVIDPILOT SUPPORT</span><h2>How can we help?</h2><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={7} required/></label>{notice&&<p className="portal-notice">{notice}</p>}<button>Submit request</button></form><div className="support-history"><span className="portal-kicker">REQUEST HISTORY</span><h2>Recent requests</h2>{data.support.length?data.support.map(s=><article key={s.id}><div><strong>{s.subject}</strong><span>{s.status}</span></div><p>{s.message}</p><small>{date(s.created_at)} · {s.priority}</small></article>):<p className="empty">No support requests yet.</p>}</div></section>}
 </section></main>
}
