"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import "./onboarding.css";
type Row=Record<string,any>;
export default function Onboarding(){
 const[data,setData]=useState<any>({items:[],clients:[]});const[selected,setSelected]=useState<Row|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/admin/onboarding",{cache:"no-store",credentials:"include"});if(r.status===401){location.href="/admin";return}const d=await r.json();setData(d);if(selected){const n=d.items?.find((x:Row)=>x.id===selected.id);if(n)setSelected(n)}}
 useEffect(()=>{load()},[]);
 async function provision(){if(!selected)return;setBusy(true);setMsg("");const l=selected.lead||{};const r=await fetch("/api/admin/onboarding",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"provision",proposal_id:selected.id,company:l.company,contact_name:l.name,email:l.email,project_name:selected.title,project_description:selected.content?.recommended_solution||"",starts_at:(document.getElementById("ob-start") as HTMLInputElement)?.value||null,target_date:(document.getElementById("ob-target") as HTMLInputElement)?.value||null})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMsg(d.error||"Onboarding failed.");return}setMsg(`Client onboarding created${d.reset_sent?" and portal setup email sent":""}.`);await load();if(d.client_id)location.href=`/admin/clients/${d.client_id}`}
 return <main className="onboarding-shell"><nav className="ops-nav"><Link href="/admin">Lead Cockpit</Link><Link href="/admin/analytics">Analytics</Link><Link href="/admin/copy-studio">AI Copy Studio</Link><Link href="/admin/proposals">Proposals</Link><Link href="/admin/clients">Clients</Link><Link className="active" href="/admin/onboarding">Onboarding</Link></nav><header><span>DAVIDPILOT · CLIENT OPERATIONS</span><h1>Client Onboarding</h1><p>Turn accepted proposals into delivery-ready client workspaces.</p></header>{msg&&<p className="ob-message">{msg}</p>}<section className="ob-grid"><aside className="ob-queue"><span>ACCEPTED PROPOSALS</span><h2>Ready to onboard</h2>{data.items?.length?data.items.map((p:Row)=><button key={p.id} className={selected?.id===p.id?"active":""} onClick={()=>setSelected(p)}><strong>{p.lead?.company||p.title}</strong><small>{p.title}</small><em>{p.client_id?"Workspace linked":"Needs provisioning"}</em></button>):<p>No accepted proposals waiting for onboarding.</p>}</aside><section className="ob-panel">{selected?<><div className="ob-head"><div><span>ACCEPTED</span><h2>{selected.lead?.company||selected.title}</h2><p>{selected.lead?.name} · {selected.lead?.email}</p></div><strong>€{selected.investment_min??"—"} – €{selected.investment_max??"—"}</strong></div><div className="ob-summary"><label>Project<input value={selected.title||""} readOnly/></label><label>Timeline<input value={selected.timeline||"TBD"} readOnly/></label><label>Start date<input id="ob-start" type="date"/></label><label>Target date<input id="ob-target" type="date"/></label></div><article><span>SCOPE</span><p>{selected.content?.recommended_solution||"Accepted proposal will be used as the initial project scope."}</p></article><article><span>AUTOMATION</span><ul><li>Create or activate client workspace</li><li>Create initial delivery project</li><li>Create onboarding checklist</li><li>Link accepted proposal to client</li><li>Create portal account when needed</li><li>Send secure password setup email when a new portal account is created</li></ul></article><button className="provision" disabled={busy} onClick={provision}>{busy?"Provisioning…":selected.client_id?"Start onboarding":"Onboard client"}</button></>:<div className="ob-empty"><strong>Select an accepted proposal</strong><p>Review the commercial context and provision the client when you are ready.</p></div>}</section></section></main>
}